@startuml

scale 1920 width

<style>
stateDiagram {
  BackgroundColor grey
  'LineColor white
  FontName Impact
  FontColor white
  arrow {
    FontSize 13
    LineColor black
  }
}
</style>



[*] -> setup : Entry point

state setup ##[bold]cyan {
    [*] --> octave
    note: substate, loop
    [*] --> tune
    [*] --> show_hz

    state octave {
        octave: 1 to 7
    }
    state tune {
        tune: C, C#, D, D#, E, F, F#, G, G#, A, A#, B
    }
    state show_hz {
    show_hz: microbit display
    }


    octave --> [*]
    tune --> [*]
    show_hz --> [*]

}
setup -> origin : Succeeded


state origin ##[bold]magenta {
    origin: map current x, y, z
    origin: movement values to 0
    origin: in retalion of physical world
}
origin -> play : Succeeded


state play ##[bold]yellow {
    [*] --> process
    state process ##[bold]green {
        process: if  20 cycles has completed
    }
    process --> sense : Succeeded
 

    state sense ##[bold]red {
    [*] --> x_movement : Entry point
    x_movement -> y_movement: Succeeded
    y_movement --> [*]: Succeeded
    }
    sense --> send : Succeeded
 

    state send ##[bold]blue {
        send: binary protocol
    }
    send --> process: Succeeded
}
play -> [*] : Disconnected

@enduml
