@startuml

scale 1920 width

<style>
stateDiagram {
  BackgroundColor grey
  'LineColor white
  FontName Impact
  FontColor white
  arrow {
    FontSize 13
    LineColor black
  }
}
</style>



[*] -> setup : Entry point

state setup ##[bold]cyan {
    [*] --> select_octave
    note: substate, loop
    [*] --> tune_note
    [*] --> show_hz

    state select_octave {
        select_octave: 1 to 7
    }
    state tune_note {
        tune_note: C, C#, D, D#, E, F, F#, G, G#, A, A#, B
    }
    state show_hz {
    show_hz: microbit display
    }


    select_octave --> [*]
    tune_note --> [*]
    show_hz --> [*]

}
setup -> set_world_position : Succeeded


state set_world_position ##[bold]magenta {
 set_world_position: map current x, y, z
 set_world_position: movement values to 0
 set_world_position: in retalion of physical world
}
set_world_position -> play_insturment : Succeeded



state play_insturment ##[bold]yellow {
 state sense ##[bold]red {
  [*] --> x_movement : Entry point
  x_movement -> y_movement: Succeeded
  y_movement -> z_movement: Succeeded
  z_movement -> x_rotation: Succeeded
  x_rotation -> y_rotation: Succeeded
  y_rotation -> z_rotation: Succeeded
  z_rotation --> [*]: Succeeded
 }
 sense --> process : Succeeded
 

state process ##[bold]green {
 }
 process --> play : Succeeded
 


state play ##[bold]blue {
 }
 play --> sense: Succeeded
}

play_insturment -> [*] : Disconected

@enduml
