@startuml

scale 1024 width

[*] -> setup

state setup {
 [*] --> select_octave
 select_octave: 1 to 7
 select_octave --> select_note : Succeeded
 select_note: C, C#, D, D#, E, F, F#, G, G#, A, A#, B
 select_note --> show_hz : Succeeded
 show_hz: microbit display
 show_hz --> [*] : Succeeded
}
setup -> set_world_position : Succeeded


state set_world_position {
 set_world_position: map current x, y, z
 set_world_position: movement values to 0
 set_world_position: in retalion of physical world
}
set_world_position -> play_insturment : Succeeded


state play_insturment {
 [*] --> x_movement
 x_movement --> y_movement: Succeeded
 y_movement --> z_movement: Succeeded
 z_movement --> x_rotation: Succeeded
 x_rotation --> y_rotation: Succeeded
 y_rotation --> z_rotation: Succeeded
 z_rotation --> process_sound : Succeeded
 process_sound --> play_sound: Succeeded

 play_sound --> x_movement: Succeeded
}

play_insturment -> [*] : Disconected

@enduml
